### ISSUE TITLE
Bug on calculating weight averages

### ISSUE THREAD

**Issue by carlosrrod** [carlosrrod/pyweight#1]
This script is reading data from a JSON file (`log_data.json`). Weight values are added up and an average weight is calculated and stored back into the `log_data.json` file. However, the average is not being calculated properly, it appears to be a bug when reading the stored weight values.

**Comment by SeniorTest** [comment]
Hi Carlos,

you are not adding the weight, which has been passed as parameter into your calculation. Only the weights stored in the json file are used for the calculation.
Adding weight_values += weight to your calculation does result into the expected average.

         weight_values += weight

        if log_counter == 1:
            weight_average = weight_values
        else:
            weight_average = weight_values / log_counter

Kind regards,

Jan

**Comment by carlosrrod** [comment]
@SeniorTest 
Yes I see where I made the mistake, by not setting `weight_values = weight` I was instead setting it to `0` which is why the average was not being calculated properly. Thank you for helping me see this mistake. I appreciate the help! 

If you'd like, you can create a pull request and I'd be happy to merge it into the project

*Carlos*
