### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by carlosrrod** [carlosrrod/pyweight#2]
This script works fine when more than one weight value has been logged, however if it finds only one, it throws the following error:
```shell
Traceback (most recent call last):
  File "pyweight.py", line 134, in <module>
    welcome()
  File "pyweight.py", line 130, in welcome
    read_log()
  File "pyweight.py", line 116, in read_log
    f"\n| Total Log Entries: {json_data['meta']['total logs']} | Average Weight: {json_data['meta']['average']} |\n")
TypeError: list indices must be integers or slices, not str
```

**Comment by SeniorTest** [comment]
Hi Carlos,

I could not figure out how to create a branch from your repo and a Pull Request afterwards, thus I am writing what I figured out.

In function log_weight you are checking if the file exists, if it doesn't you are creating an array/list containing the meta data, see

`"meta": [
                {
                    "average": weight,
                    "total logs": 1
                }
            ]`

But if the file exists, meta gets overwritten by a dictionary

`new_weight_log = {
            "weight": weight,
            "date": today,
            "log#": log_counter
        }
        json_data['log entry'].append(new_weight_log)
        json_data['meta'] = new_meta_log`

The resulting json structure is different for 1 element than for many elements.

As far as I understand it does not need to be a list, thus I changed it here to 
`    else:
        new_weight_log = {
            "log entry": [
                {
                    "weight": weight,
                    "date": today,
                    "log#": 1
                }
            ],
            "meta": {
                "average": weight,
                "total logs": 1
            }
        }
        with open('log_data.json', 'a') as log:
            json.dump(new_weight_log, log, indent=2)`

That way the json structure is the same, no matter if it is the first or any other entry.

Kind regards,

Jan

**Comment by carlosrrod** [comment]
@SeniorTest You are absolutely right, I forgot to make sure the JSON was the same with between a single log and multiple logs. Thank you for pointing this out. As for creating a Pull Request, you first need to Fork this repo, this will create a copy of the repo onto your machine, once you make changes on your repo you can submit a Pull Request.  
- Learn about forking [here](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)
- Learn about making pull requests here: [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

I'd like you to receive credit for contributing to this project so I encourage you to make a pull request!, If not, that's ok too! Thanks again for taking the time to help.

*Carlos*
